### ISSUE TITLE
Error al cerrar sesión y volver a abrirla

### ISSUE THREAD

**Issue by RIranzo** [UNIZAR-30226-2022-05/Frontend-Escritorio#1]
Cuando se cierra sesión manualmente no se puede volver a abrir (no cambia a la siguiente pantalla). Creo que se queda en el paso intermedio entre pedir la clave de inicio y conectarse con websockets, pues dandole una vez no pasa nada, y a la siguiente sale que el usuario ya tiene una sesión iniciada o está iniciando una (creo que lo segundo, porque no se llega a conectar con websockets).

**Comment by Gabinsito** [comment]
Arreglado el bug. El bug se producía porque siempre que se iba a la pantalla de login  se cerraba la conexión. Ahora lo que se hace es cerrar la conexión sólo desde los botones de dentro de la app, y además se crea un nuevo objeto WebSocketApi, porque al intentar iniciar sesión se llama al método apiweb.openConnection() y hay un if que hace que si está cerrado el websocket, se sale de la función sin llegar a abrirlo.
